function [ Throughput ] = ReadThroughputExtractedFile( filename )
% Read the Throughputs from Extracted File
%   The Extracted file is generated by ./collectThroughput.sh and tcptrace

if strcmp(filename,'')
    filename = 'Throughput.txt';
end
    tempStr = fileread(filename);
    throughputStr = regexp(tempStr,'[1-9]+[0-9]*\s','match');
    throughputStr = char(deblank(throughputStr));
    Throughput = [str2num(throughputStr)]';
end

